// performance-testing/angular-test/src/app/table/table.component.ts
import { Component, OnInit, Input } from "@angular/core";

@Component({
  selector: "app-table",
  templateUrl: "./table.component.html",
  styleUrls: ["./table.component.css"]
})
export class TableComponent implements OnInit {
  @Input() items: Object;
  constructor() {}

  ngOnInit() {}
}

<table>
  <thead>
    <tr>
      <td>Key</td>
      <td>Random Value</td>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let item of items">
      <td>{{ item.key }}</td>
      <td>{{ item.value }}</td>
    </tr>
  </tbody>
</table>

// performance-testing/react-test/src/components/Table.js
import React from "react";
import "./Table.css";

const Table = props => (
  <table>
    <thead>
      <tr>
        <td>Key</td>
        <td>Random Value</td>
      </tr>
    </thead>
    <tbody>
      {props.items &&
        props.items.map(item => (
          <tr key={item.key}>
            <td>{item.key}</td>
            <td>{item.value}</td>
          </tr>
        ))}
    </tbody>
  </table>
);

export default Table;
