// hello-world/todo-app/react-todo/src/components/TodoList.js
import React from "react";
import "./TodoList.css";

class TodoList extends React.Component {
  render() {
    const { todos } = this.props;
    if (!todos || todos.length === 0) {
      return <p className="no-items">You finished all your todos!</p>;
    }
    return (
      <ul className="todo-list">
        {todos.map(todo => (
          <li key={todo.id}>
            <label htmlFor={`check-${todo.id}`}>
              <input
                type="checkbox"
                id={`check-${todo.id}`}
                checked={todo.completed}
                onChange={this.props.toggleCompleted.bind(this, todo.id)}
              />
              <span className={todo.completed ? "strike" : ""}>
                {todo.name}
              </span>
            </label>
          </li>
        ))}
      </ul>
    );
  }
}

export default TodoList;

// todo-app/angular-todo/src/app/todo-list/todo-list.component.ts
import { Component, OnInit, Input } from "@angular/core";
import { Todo } from "../Todo";
@Component({
  selector: "app-todo-list",
  templateUrl: "./todo-list.component.html",
  styleUrls: ["./todo-list.component.css"]
})
export class TodoListComponent implements OnInit {
  @Input() todos: Todo[];

  constructor() {}

  ngOnInit() {}
}

<ul class="todo-list">
  <li key="{todo.id}" *ngFor="let todo of todos; let index = index">
    <label>
      <input type="checkbox" [(ngModel)]="todo.completed" />
      <span [class]="todo.completed ? 'strike' : ''"> {{ todo.name }} </span>
    </label>
  </li>
</ul>
