// todo-app/vue-todo/src/components/TodoList.vue
<template>
  <ul class="todo-list">
    <li v-bind:key="todo.id" v-for="todo of todos">
      <label :for="checkboxId(todo.id)">
        <input type="checkbox" :id="checkboxId(todo.id)" v-model="todo.completed">
        <span :class="todo.completed ? 'strike' : ''">{{todo.name}}</span>
      </label>
    </li>
  </ul>
</template>

<script>
export default {
  name: "TodoList",
  props: ["todos"],
  methods: {
    checkboxId(id) {
      return `check-${id}`;
    }
  }
};
</script>

<style scoped>
.todo-list {
  list-style: none;
  display: flex;
  flex-direction: column;
  justify-content: center;
  justify-items: flex-start;
  text-align: left;
  margin: 1rem;
}

li {
  font-size: 2rem;
}

li input[type="checkbox"] {
  transform: scale(1.5);
  margin-right: 0.5rem;
}

.strike {
  text-decoration: line-through;
}

.no-items {
  margin: 1rem;
}
</style>

// hello-world/todo-app/react-todo/src/components/TodoList.js
import React from "react";
import "./TodoList.css";

class TodoList extends React.Component {
  render() {
    const { todos } = this.props;
    if (!todos || todos.length === 0) {
      return <p className="no-items">You finished all your todos!</p>;
    }
    return (
      <ul className="todo-list">
        {todos.map(todo => (
          <li key={todo.id}>
            <label htmlFor={`check-${todo.id}`}>
              <input
                type="checkbox"
                id={`check-${todo.id}`}
                checked={todo.completed}
                onChange={this.props.toggleCompleted.bind(this, todo.id)}
              />
              <span className={todo.completed ? "strike" : ""}>
                {todo.name}
              </span>
            </label>
          </li>
        ))}
      </ul>
    );
  }
}

export default TodoList;
